apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: inventory-db
spec:
  selector:
    matchLabels:
      app: inventory-db
  serviceName: inventory-db-service
  replicas: 1
  template:
    metadata:
      labels:
        app: inventory-db
    spec:
      containers:
      - name: inventory-db
        image: postgres:16
        resources:
          limits:
              memory: "200Mi"
              cpu: "200m"
          requests:
            memory: "100Mi"
            cpu: "100m"
        env:
          - name: POSTGRES_USER
#            value: "postgres"
            #8.5 ConfigMap & secrets in kubernetes
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: INVENTORY_DB_USER
          - name: POSTGRES_PASSWORD
#            value: "1234"
            #8.5 ConfigMap & secrets in kubernetes
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: INVENTORY_DB_PASSWORD
          - name: POSTGRES_DB
#            value: "inventoryDB"
            #8.5 ConfigMap & secrets in kubernetes
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: INVENTORY_DB_NAME

          - name: PGDATA
#            value: /var/lib/postgresql/data/pgdata
            #8.5 ConfigMap & secrets in kubernetes
            valueFrom:
              configMapKeyRef:
                name: my-config
                key: PG_DATA
        ports:
        - containerPort: 5432  
          name: postgres
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
      storageClassName: "standard-rwo" 
      volumeMode: Filesystem

---

apiVersion: v1
kind: Service
metadata:
  name: inventory-db-service
spec:
  clusterIP: None
  selector:
    app: inventory-db
  ports:
  - port: 5432
    targetPort: 5432
